// Updated language.js with new translations for all pages
const translations = {
  en: {
    // === General ===
    title: 'Educational Platform',
    home: 'Main',
    about: 'About',
    programs: 'Programs',
    reviews: 'Reviews',
    team: 'Team',
    partners: 'Partners',
    login: 'Login',
    logout: 'Logout',
    profile: 'Profile',
    settings: 'Settings',
    close: 'Close',
    loading: 'Loading...',
    not_specified: 'Not specified',
    save_changes: 'Save Changes',
    all_rights_reserved: '2025 EDU-Familiar.kz. All rights reserved.',
    control_server: 'Control Server',
    teacher_dashboard_link: 'Development Area',
    
    // === Footer / About ===
    about_edu: 'About EDU-Familiar.kz',
    footer_about_desc: 'We are a leading educational platform in Kazakhstan, offering cutting-edge courses to prepare students for the future.',
    quick_links: 'Quick Links',
    our_programs: 'Our Programs',
    student_reviews: 'Student Reviews',
    meet_the_team: 'Meet the Team',
    our_partners: 'Our Partners',
    faq: 'FAQ',
    contact_us: 'Contact Us',
    email_label: 'Email:',
    phone_label: 'Phone:',
    address_label: 'Address:',
    follow_us: 'Follow Us',
    language: 'Language',
    copyright: '2025 EDU-Familiar.kz. All rights reserved.',

    // === Login/Register (from old file) ===
    register_title: 'Registration',
    email: 'Email',
    password: 'Password',
    confirm_password: 'Confirm Password',
    region: 'Region of Residence',
    user_type: 'User Type',
    login_title: 'Login',
    register: 'Register',
    info_banner_title: 'About EDU-Familiar.kz',
    how_to_register: 'How to Register',
    register_info_desc: 'To join our platform, click the "Register Now" button, fill in your details including name, email, and password, choose your region and user type, and submit the form. You\'ll receive a confirmation email to start your learning journey.',
    why_us: 'Why Us',
    why_us_desc: 'EDU-Familiar.kz offers cutting-edge courses tailored to modern industry needs, with a focus on practical skills and accessibility for all learners in Kazakhstan and beyond.',
    why_choose_us: 'Why Choose Us',
    why_choose_desc: 'Our platform combines expert instruction, flexible learning...',

    // === Profile Page (profile.php) ===
    profile_title: 'Profile',
    user_name: 'Name',
    user_class: 'Class',
    user_type_label: 'Type:',
    level_1: 'Level 1',
    achievements: 'Achievements',
    achievement1: 'Completed Introduction to Coding',
    achievement2: 'Earned Data Science Badge',
    leaders: 'Leaders',
    your_position: 'Your Position',
    motivational_title: 'Keep Learning and Achieve More!',
    motivational_desc: 'Every step you take brings you closer to your goals. Stay motivated!',
    highest_score: 'Highest Score',
    highest_score_value: 'Best Score: 950 points',
    cta_tasks_title: 'Take on New Tasks!',
    cta_tasks_desc: 'Challenge yourself with new assignments to boost your skills!',
    explore_tasks: 'Explore Tasks',
    course_recommendations: 'Course Recommendations',
    recommendation1: 'Try Advanced Python Course',
    recommendation2: 'Explore Machine Learning Basics',
    certificates: 'Certificates',
    certificate1: 'Certificate: Introduction to Coding, 10.10.2025',
    certificate2: 'Certificate: Data Science Basics, 15.09.2025',

    // === Best Students Page (best-students.php) ===
    best_students_title: 'Best Students',
    rank: 'Rank',
    avatar: 'Avatar',
    points: 'Total Points',
    prev_page: 'Previous Page',
    next_page: 'Next Page',

    // === Settings Modal (profile.php, best-students.php, etc.) ===
    profile_settings: 'Profile Settings',
    upload_avatar: 'Upload Avatar',
    user_info: 'Your Info',
    username: 'Username:',
    full_name: 'Full Name:',
    class_label: 'Class:',
    edit_profile: 'Edit Profile',
    new_username: 'New Username',
    new_fullname: 'New Full Name',
    class_select: 'Class',
    select_class_empty: '—',
    avatar_border_settings: 'Avatar Border Settings',
    standard: 'Standard',
    efpremium: 'EFPremium',
    border_color: 'Border Color',
    border_preview: 'Preview:',
    frame_rgb: 'RGB',
    efpremium_required_frames: 'Get EFPremium to access exclusive frames!',
    get_premium: 'Get EFPremium',
    save_border: 'Save Border',

    // === Teacher Dashboard (teacher_dashboard.php) ===
    teacher_dashboard_title: 'Development Area',
    teacher_dashboard_desc: 'Welcome to the content control panel. Here you can create materials for students.',
    stat_books_loaded: 'Books Loaded',
    stat_avg_rating: 'Average Rating',
    tools_title: 'Tools',
    add_book_title: 'Add Book',
    add_book_desc: 'Upload a new PDF textbook or guide.',
    my_publications_title: 'My Publications',
    my_publications_desc: 'View your uploaded materials in the library.',
    create_test_title: 'Create Test',
    create_test_desc: 'Constructor for interactive assignments.',
    analytics_title: 'Analytics',
    analytics_desc: 'View statistics and student performance.',
    dev_in_progress: 'Functionality in development!',

    // === Add/Edit Book (add_book.php, edit_book.php) ===
    add_book_page_title: 'Add Book',
    add_book_header: 'Add a new book',
    add_book_subheader: 'Fill out the form to publish material in the library.',
    edit_book_page_title: 'Edit Book',
    edit_book_header: 'Edit Book',
    edit_book_subheader: 'Change information or upload updated files.',
    book_title_label: 'Book Title',
    book_title_placeholder: 'Example: Physics 7th Grade. Mechanics',
    subject_label: 'Subject',
    select_subject_placeholder: 'Select subject',
    // Subjects
    subject_math: 'Mathematics',
    subject_algebra: 'Algebra',
    subject_geometry: 'Geometry',
    subject_physics: 'Physics',
    subject_chemistry: 'Chemistry',
    subject_biology: 'Biology',
    subject_english: 'English',
    subject_history: 'History',
    subject_informatics: 'Informatics',
    subject_literature: 'Literature',
    subject_geography: 'Geography',
    subject_russian: 'Russian Language',
    subject_russian_lit: 'Russian Literature',
    subject_russian_lang_lit: 'Russian Language and Literature',
    subject_kazakh: 'Kazakh Language',
    subject_kazakh_lang_lit: 'Kazakh Language and Literature',
    subject_natural_science: 'Natural Science',
    subject_world_history: 'World History',
    subject_kazakh_history: 'History of Kazakhstan',
    subject_global_comp: 'Global Competencies',
    subject_law_basics: 'Basics of Law',
    subject_self_knowledge: 'Self-Knowledge',
    subject_labor_training: 'Labor Training',
    subject_art: 'Fine Arts',
    subject_music: 'Music',
    subject_art_labor: 'Artistic Labor',
    subject_pe: 'Physical Education',
    subject_military_training: 'Basic Military and Technological Training',
    // End Subjects
    class_label_form: 'Class',
    n_class: '{n} Grade', // Example for loops, though PHP loop is static
    languages_label: 'Book Languages',
    lang_ru: 'Russian',
    lang_kz: 'Kazakh',
    lang_en: 'English',
    short_desc_label: 'Short Description (for card)',
    short_desc_placeholder: 'Max 150 characters...',
    full_desc_label: 'Full Description',
    full_desc_placeholder: 'Detailed description of the learning material...',
    cover_label: 'Cover (JPG, PNG)',
    cover_desc: 'Recommended size: 300x450px (Vertical)',
    file_label: 'Book File (PDF)',
    publish_button: 'Publish Book',
    save_button: 'Save Changes',
    cancel_button: 'Cancel',
    edit_book_leave_empty: '(Leave empty if not changing)',
    current_cover_label: 'Current cover:',
    current_file_label: 'Current file:',
    alert_book_published: 'Book published successfully!',
    alert_book_saved: 'Changes saved!',
    alert_db_error: 'DB Error:',
    alert_upload_error: 'File upload error.',
    
    // === My Books (my_books.php) ===
    my_publications_page_title: 'My Publications',
    my_publications_desc: 'Manage your uploaded books and materials',
    add_book_button: 'Add',
    edit_button: 'Edit',
    delete_button: 'Delete',
    view_button: 'View',
    empty_state_title: 'You have no publications yet',
    empty_state_desc: 'Upload your first book or study material.',
    empty_state_add_button: 'Add Book',
    confirm_delete_message: 'Are you sure you want to delete this book? This action is irreversible.',
    alert_delete_success: 'Book deleted successfully.',
    alert_delete_error: 'Delete error. You are not the author of this book.',

    // === Online Book (online-book.php) ===
    online_library_title: 'Online Library',
    filter_class_label: 'Class',
    filter_all_classes: 'All Classes',
    filter_search_label: 'Search',
    filter_search_placeholder: 'Book title or subject...',
    filter_find_button: 'Find',
    books_not_found: 'Books not found. Try changing the filters.',
    open_button: 'Open',
    
    // === Book Details (book_details.php) ===
    back_to_library: 'Back to library',
    read_online_button: 'Read Online',
    download_pdf_button: 'Download PDF',
    author_support_notice: 'The author will receive support for views',
    rating_votes_label: 'Based on {n} votes',
    description_label: 'Material Description',
    your_rating_label: 'Your rating for the material',
    rating_5_star: 'Excellent',
    rating_4_star: 'Good',
    rating_3_star: 'Okay',
    rating_2_star: 'Bad',
    rating_1_star: 'Awful',
    author_label: 'Publication Author',
    report_error_link: 'Found an error? Report',
    report_error_alert: 'The report function is temporarily unavailable. We are working on it!',
    alert_rating_login: 'Please log in to rate the book.',

    // === Training Page (from old file) ===
    training: 'Training',
    best_students: 'Best Students',
    training_title: 'Training - EDU-Familiar.kz',
    filters: 'Filters',
    rating: 'Rating',
    class_program: 'Class Program',
    sort_by: 'Sort By',
    new_courses: 'New Courses',
    old_courses: 'Old Courses',
    popular: 'Popular',
    search_placeholder: 'Search courses...',
    course_rating: 'Rating:',
    course_date: 'Created:',
    course_teacher: 'Teacher:',
    no_courses: 'No courses found.',
    online_book_title: 'Online Book - EDU-Familiar.kz',
    online_book: 'Online Book',
    books_list: 'Available Books',
    read_online: 'Read Online',
    download: 'Download',
    no_books: 'No books available.',
    book_rating: 'Rating:',
    book_class: 'Class:',

    // === Catalog (from old file) ===
    catalog_title: 'Catalog - EDU-Familiar.kz',
    catalog: 'Catalog',
    mugs: 'Mugs',
    mug1_name: 'Mug "Kitty"',
    mug2_name: 'Mug "Motivation"',
    mug3_name: 'Mug "Love"',
    mug4_name: 'Mug "Nature"',
    mug5_name: 'Mug "Space"',
    mug6_name: 'Mug "Minimalism"',
    backpacks: 'Backpacks',
    backpack1_name: 'Backpack "Urban"',
    backpack2_name: 'Backpack "Sport"',
    backpack3_name: 'Backpack "Classic"',
    backpack4_name: 'Backpack "Travel"',
    backpack5_name: 'Backpack "Minimal"',
    backpack6_name: 'Backpack "Eco"',
    tshirts: 'Tshirts',
    tshirt1_name: 'Tshirt "Print"',
    tshirt2_name: 'Tshirt "Classic"',
    tshirt3_name: 'Tshirt "Sport"',
    tshirt4_name: 'Tshirt "Vintage"',
    tshirt5_name: 'Tshirt "Minimalism"',
    tshirt6_name: 'Tshirt "Eco"',
    caps: 'Caps',
    cap1_name: 'Cap "Classic"',
    cap2_name: 'Cap "Snapback"',
    cap3_name: 'Cap "Baseball"',
    cap4_name: 'Cap "Trucker"',
    cap5_name: 'Cap "Vintage"',
    cap6_name: 'Cap "Eco"',
    notebooks: 'Notebooks',
    notebook1_name: 'Notebook A5 "Minimal"',
    notebook2_name: 'Notebook A5 "Print"',
    notebook3_name: 'Notebook A6 "Travel"',
    notebook4_name: 'Notebook A5 "Space"',
    notebook5_name: 'Notebook A5 "Flora"',
    notebook6_name: 'Notebook A6 "Minimalism"',
    show_more: 'Show More',
    all_shown: 'All Products Shown',
  },
  ru: {
    // === General ===
    title: 'Образовательная платформа',
    home: 'Главная',
    about: 'О нас',
    programs: 'Программы',
    reviews: 'Отзывы',
    team: 'Команда',
    partners: 'Партнеры',
    login: 'Войти',
    logout: 'Выход',
    profile: 'Профиль',
    settings: 'Настройки',
    close: 'Закрыть',
    loading: 'Загрузка...',
    not_specified: 'Не указано',
    save_changes: 'Сохранить изменения',
    all_rights_reserved: '2025 EDU-Familiar.kz. Все права защищены.',
    control_server: 'Control Server',
    teacher_dashboard_link: 'Сфера разработки',
    
    // === Footer / About ===
    about_edu: 'О EDU-Familiar.kz',
    footer_about_desc: 'Мы — ведущая образовательная платформа в Казахстане, предлагающая передовые курсы для подготовки студентов к будущему.',
    quick_links: 'Быстрые ссылки',
    our_programs: 'Наши программы',
    student_reviews: 'Отзывы студентов',
    meet_the_team: 'Знакомьтесь с командой',
    our_partners: 'Наши партнеры',
    faq: 'FAQ',
    contact_us: 'Связаться с нами',
    email_label: 'Email:',
    phone_label: 'Телефон:',
    address_label: 'Адрес:',
    follow_us: 'Следите за нами',
    language: 'Язык',
    copyright: '2025 EDU-Familiar.kz. Все права защищены.',

    // === Login/Register (from old file) ===
    register_title: 'Регистрация',
    email: 'Email',
    password: 'Пароль',
    confirm_password: 'Подтвердите пароль',
    region: 'Регион проживания',
    user_type: 'Тип пользователя',
    login_title: 'Вход',
    register: 'Зарегистрироваться',
    info_banner_title: 'О EDU-Familiar.kz',
    how_to_register: 'Как зарегистрироваться',
    register_info_desc: 'Чтобы присоединиться к нашей платформе, нажмите кнопку «Зарегистрироваться сейчас», заполните свои данные, включая имя, email и пароль, выберите свой регион и тип пользователя, и отправьте форму. Вы получите письмо с подтверждением, чтобы начать свое учебное путешествие.',
    why_us: 'Почему мы',
    why_us_desc: 'EDU-Familiar.kz предлагает передовые курсы, адаптированные к нуждам современной промышленности, с акцентом на практические навыки и доступность для всех учащихся в Казахстане и за его пределами.',
    why_choose_us: 'Почему выбрать нас',
    why_choose_desc: 'Наша платформа сочетает экспертное обучение, гибкое обучение...',

    // === Profile Page (profile.php) ===
    profile_title: 'Профиль',
    user_name: 'Имя',
    user_class: 'Класс',
    user_type_label: 'Тип:',
    level_1: 'Уровень 1',
    achievements: 'Достижения',
    achievement1: 'Завершен «Введение в программирование»',
    achievement2: 'Получен значок Data Science',
    leaders: 'Лидеры',
    your_position: 'Ваша позиция',
    motivational_title: 'Продолжайте учиться и достигайте большего!',
    motivational_desc: 'Каждый шаг приближает вас к вашим целям. Оставайтесь мотивированными!',
    highest_score: 'Самый высокий балл',
    highest_score_value: 'Лучший результат: 950 очков',
    cta_tasks_title: 'Беритесь за новые задания!',
    cta_tasks_desc: 'Поставьте себе вызов с новыми заданиями, чтобы повысить свои навыки!',
    explore_tasks: 'Исследовать задания',
    course_recommendations: 'Рекомендации курсов',
    recommendation1: 'Попробуйте продвинутый курс по Python',
    recommendation2: 'Исследуйте основы машинного обучения',
    certificates: 'Сертификаты',
    certificate1: 'Сертификат: Введение в программирование, 10.10.2025',
    certificate2: 'Сертификат: Основы Data Science, 15.09.2025',

    // === Best Students Page (best-students.php) ===
    best_students_title: 'Лучшие студенты',
    rank: 'Ранг',
    avatar: 'Аватар',
    points: 'Общее количество очков',
    prev_page: 'Предыдущая страница',
    next_page: 'Следующая страница',

    // === Settings Modal (profile.php, best-students.php, etc.) ===
    profile_settings: 'Настройки профиля',
    upload_avatar: 'Загрузить аватар',
    user_info: 'Ваши данные',
    username: 'Логин:',
    full_name: 'ФИО:',
    class_label: 'Класс:',
    edit_profile: 'Редактировать',
    new_username: 'Новый логин',
    new_fullname: 'Новое ФИО',
    class_select: 'Класс',
    select_class_empty: '—',
    avatar_border_settings: 'Оформление аватара',
    standard: 'Standard',
    efpremium: 'EFPremium',
    border_color: 'Цвет рамки',
    border_preview: 'Превью:',
    frame_rgb: 'RGB',
    efpremium_required_frames: 'Получите EFPremium для доступа к эксклюзивным рамкам!',
    get_premium: 'Получить EFPremium',
    save_border: 'Сохранить рамку',

    // === Teacher Dashboard (teacher_dashboard.php) ===
    teacher_dashboard_title: 'Сфера Разработки',
    teacher_dashboard_desc: 'Добро пожаловать в панель управления контентом. Здесь вы можете создавать материалы для студентов.',
    stat_books_loaded: 'Загружено книг',
    stat_avg_rating: 'Средний рейтинг',
    tools_title: 'Инструменты',
    add_book_title: 'Добавить Книгу',
    add_book_desc: 'Загрузить новый PDF учебник или методичку.',
    my_publications_title: 'Мои Публикации',
    my_publications_desc: 'Просмотр ваших загруженных материалов в библиотеке.',
    create_test_title: 'Создать Тест',
    create_test_desc: 'Конструктор интерактивных заданий.',
    analytics_title: 'Аналитика',
    analytics_desc: 'Статистика просмотров и успеваемости.',
    dev_in_progress: 'Функция в разработке!',
    
    // === Add/Edit Book (add_book.php, edit_book.php) ===
    add_book_page_title: 'Добавить книгу',
    add_book_header: 'Добавить новую книгу',
    add_book_subheader: 'Заполните форму, чтобы опубликовать материал в библиотеке.',
    edit_book_page_title: 'Редактировать книгу',
    edit_book_header: 'Редактировать книгу',
    edit_book_subheader: 'Измените информацию или загрузите обновленные файлы.',
    book_title_label: 'Название книги',
    book_title_placeholder: 'Например: Физика 7 класс. Механика',
    subject_label: 'Предмет',
    select_subject_placeholder: 'Выберите предмет',
    // Subjects
    subject_math: 'Математика',
    subject_algebra: 'Алгебра',
    subject_geometry: 'Геометрия',
    subject_physics: 'Физика',
    subject_chemistry: 'Химия',
    subject_biology: 'Биология',
    subject_english: 'Английский язык',
    subject_history: 'История',
    subject_informatics: 'Информатика',
    subject_literature: 'Литература',
    subject_geography: 'География',
    subject_russian: 'Русский язык',
    subject_russian_lit: 'Русская литература',
    subject_russian_lang_lit: 'Русский язык и литература',
    subject_kazakh: 'Казахский язык',
    subject_kazakh_lang_lit: 'Казахский язык и литература',
    subject_natural_science: 'Естествознание',
    subject_world_history: 'Всемирная История',
    subject_kazakh_history: 'История Казахстана',
    subject_global_comp: 'Глобальные компетенции',
    subject_law_basics: 'Основы права',
    subject_self_knowledge: 'Самопознание',
    subject_labor_training: 'Трудовое обучение',
    subject_art: 'Изобразительное искусство',
    subject_music: 'Музыка',
    subject_art_labor: 'Художественный труд',
    subject_pe: 'Физическая культура',
    subject_military_training: 'Начальная военная и технологическая подготовка',
    // End Subjects
    class_label_form: 'Класс',
    n_class: '{n} Класс',
    languages_label: 'Языки книги',
    lang_ru: 'Русский',
    lang_kz: 'Казахский',
    lang_en: 'Английский',
    short_desc_label: 'Краткое описание (для карточки)',
    short_desc_placeholder: 'Максимум 150 символов...',
    full_desc_label: 'Полное описание',
    full_desc_placeholder: 'Подробное описание учебного материала...',
    cover_label: 'Обложка (JPG, PNG)',
    cover_desc: 'Рекомендуемый размер: 300x450px (Вертикальный)',
    file_label: 'Файл книги (PDF)',
    publish_button: 'Опубликовать книгу',
    save_button: 'Сохранить изменения',
    cancel_button: 'Отмена',
    edit_book_leave_empty: '(Оставьте пустым, если не меняете)',
    current_cover_label: 'Текущая обложка:',
    current_file_label: 'Текущий файл:',
    alert_book_published: 'Книга успешно опубликована!',
    alert_book_saved: 'Изменения сохранены!',
    alert_db_error: 'Ошибка БД:',
    alert_upload_error: 'Ошибка загрузки файлов.',

    // === My Books (my_books.php) ===
    my_publications_page_title: 'Мои Публикации',
    my_publications_desc: 'Управляйте вашими загруженными книгами и материалами',
    add_book_button: 'Добавить',
    edit_button: 'Изм.',
    delete_button: 'Удал.',
    view_button: 'Просмотр',
    empty_state_title: 'У вас пока нет публикаций',
    empty_state_desc: 'Загрузите свою первую книгу или учебный материал.',
    empty_state_add_button: 'Добавить книгу',
    confirm_delete_message: 'Вы уверены, что хотите удалить эту книгу? Действие необратимо.',
    alert_delete_success: 'Книга успешно удалена.',
    alert_delete_error: 'Ошибка удаления. Вы не автор этой книги.',

    // === Online Book (online-book.php) ===
    online_library_title: 'Онлайн Библиотека',
    filter_class_label: 'Класс',
    filter_all_classes: 'Все классы',
    filter_search_label: 'Поиск',
    filter_search_placeholder: 'Название книги или предмет...',
    filter_find_button: 'Найти',
    books_not_found: 'Книги не найдены. Попробуйте изменить фильтры.',
    open_button: 'Открыть',
    
    // === Book Details (book_details.php) ===
    back_to_library: 'Вернуться в библиотеку',
    read_online_button: 'Читать Онлайн',
    download_pdf_button: 'Скачать PDF',
    author_support_notice: 'Автор получит поддержку при просмотре',
    rating_votes_label: 'На основе {n} голосов',
    description_label: 'Описание материала',
    your_rating_label: 'Ваша оценка материала',
    rating_5_star: 'Отлично',
    rating_4_star: 'Хорошо',
    rating_3_star: 'Нормально',
    rating_2_star: 'Плохо',
    rating_1_star: 'Ужасно',
    author_label: 'Автор публикации',
    report_error_link: 'Нашли ошибку? Пожаловаться',
    report_error_alert: 'Функция жалоб временно недоступна. Мы работаем над этим!',
    alert_rating_login: 'Пожалуйста, авторизуйтесь, чтобы оценить книгу.',

    // === Training Page (from old file) ===
    training: 'Обучение',
    best_students: 'Лучшие студенты',
    training_title: 'Обучение - EDU-Familiar.kz',
    filters: 'Фильтры',
    rating: 'Рейтинг',
    class_program: 'Программа класса',
    sort_by: 'Сортировать по',
    new_courses: 'Новые курсы',
    old_courses: 'Старые курсы',
    popular: 'Популярные',
    search_placeholder: 'Поиск курсов...',
    course_rating: 'Рейтинг:',
    course_date: 'Создано:',
    course_teacher: 'Преподаватель:',
    no_courses: 'Курсы не найдены.',
    online_book_title: 'Онлайн Книга - EDU-Familiar.kz',
    online_book: 'Онлайн Книга',
    books_list: 'Доступные книги',
    read_online: 'Читать онлайн',
    download: 'Скачать',
    no_books: 'Книги недоступны.',
    book_rating: 'Рейтинг:',
    book_class: 'Класс:',

    // === Catalog (from old file) ===
    catalog_title: 'Каталог - EDU-Familiar.kz',
    catalog: 'Каталог',
    mugs: 'Кружки',
    mug1_name: 'Кружка "Котик"',
    mug2_name: 'Кружка "Мотивация"',
    mug3_name: 'Кружка "Любовь"',
    mug4_name: 'Кружка "Природа"',
    mug5_name: 'Кружка "Космос"',
    mug6_name: 'Кружка "Минимализм"',
    backpacks: 'Рюкзаки',
    backpack1_name: 'Рюкзак "Городской"',
    backpack2_name: 'Рюкзак "Спорт"',
    backpack3_name: 'Рюкзак "Классика"',
    backpack4_name: 'Рюкзак "Путешествие"',
    backpack5_name: 'Рюкзак "Минимал"',
    backpack6_name: 'Рюкзак "Эко"',
    tshirts: 'Футболки',
    tshirt1_name: 'Футболка "Принт"',
    tshirt2_name: 'Футболка "Классика"',
    tshirt3_name: 'Футболка "Спорт"',
    tshirt4_name: 'Футболка "Винтаж"',
    tshirt5_name: 'Футболка "Минимализм"',
    tshirt6_name: 'Футболка "Эко"',
    caps: 'Кепки',
    cap1_name: 'Кепка "Классика"',
    cap2_name: 'Кепка "Snapback"',
    cap3_name: 'Кепка "Бейсболка"',
    cap4_name: 'Кепка "Траки"',
    cap5_name: 'Кепка "Винтаж"',
    cap6_name: 'Кепка "Эко"',
    notebooks: 'Тетради',
    notebook1_name: 'Тетрадь А5 "Минимал"',
    notebook2_name: 'Тетрадь А5 "Принт"',
    notebook3_name: 'Тетрадь А6 "Путешествие"',
    notebook4_name: 'Тетрадь А5 "Космос"',
    notebook5_name: 'Тетрадь А5 "Флора"',
    notebook6_name: 'Тетрадь А6 "Минимализм"',
    show_more: 'Показать еще',
    all_shown: 'Все товары показаны',
  },
  kz: {
    // === General ===
    title: 'Білім беру платформасы',
    home: 'Басты бет',
    about: 'Біз туралы',
    programs: 'Бағдарламалар',
    reviews: 'Пікірлер',
    team: 'Команда',
    partners: 'Серіктестер',
    login: 'Кіру',
    logout: 'Шығу',
    profile: 'Профиль',
    settings: 'Баптаулар',
    close: 'Жабу',
    loading: 'Жүктелуде...',
    not_specified: 'Көрсетілмеген',
    save_changes: 'Өзгерістерді сақтау',
    all_rights_reserved: '2025 EDU-Familiar.kz. Барлық құқықтар қорғалған.',
    control_server: 'Control Server',
    teacher_dashboard_link: 'Әзірлеу саласы',
    
    // === Footer / About ===
    about_edu: 'EDU-Familiar.kz туралы',
    footer_about_desc: 'Біз Қазақстандағы жетекші білім беру платформасымыз, студенттерді болашаққа дайындау үшін ең жаңа курстар ұсынамыз.',
    quick_links: 'Тез сілтемелер',
    our_programs: 'Біздің бағдарламаларымыз',
    student_reviews: 'Студенттердің пікірлері',
    meet_the_team: 'Командамен танысыңыз',
    our_partners: 'Біздің серіктестеріміз',
    faq: 'Сұрақ-жауап',
    contact_us: 'Байланыс',
    email_label: 'Email:',
    phone_label: 'Телефон:',
    address_label: 'Мекенжайы:',
    follow_us: 'Бізді қадағалаңыз',
    language: 'Тіл',
    copyright: '2025 EDU-Familiar.kz. Барлық құқықтар қорғалған.',

    // === Login/Register (from old file) ===
    register_title: 'Тіркеу',
    email: 'Email',
    password: 'Құпиясөз',
    confirm_password: 'Құпиясөзді растау',
    region: 'Тұру аймағы',
    user_type: 'Пайдаланушы түрі',
    login_title: 'Кіру',
    register: 'Тіркелу',
    info_banner_title: 'EDU-Familiar.kz туралы',
    how_to_register: 'Қалай тіркелу керек',
    register_info_desc: 'Біздің платформаға қосылу үшін "Қазір тіркелу" батырмасын басыңыз, атыңызды, email-ді және құпиясөзді толтырыңыз, аймағыңыз бен пайдаланушы түрін таңдаңыз және форманы жіберіңіз. Сіз оқу сапарыңызды бастау үшін растау email-ін аласыз.',
    why_us: 'Неге біз',
    why_us_desc: 'EDU-Familiar.kz заманауи өнеркәсіп қажеттіліктеріне бейімделген ең жаңа курстар ұсынады, Қазақстандағы және одан тыс жерлердегі барлық оқушылар үшін практикалық дағдылар мен қолжетімділікке назар аударады.',
    why_choose_us: 'Неге бізді таңдау керек',
    why_choose_desc: 'Біздің платформа сарапшы нұсқауларын, икемді оқуды біріктіреді...',

    // === Profile Page (profile.php) ===
    profile_title: 'Профиль',
    user_name: 'Аты',
    user_class: 'Сыныбы',
    user_type_label: 'Түрі:',
    level_1: 'Деңгей 1',
    achievements: 'Жетістіктер',
    achievement1: '«Бағдарламалауға кіріспе» аяқталды',
    achievement2: 'Data Science белгісі алынды',
    leaders: 'Лидерлер',
    your_position: 'Сіздің орныңыз',
    motivational_title: 'Оқуды жалғастырыңыз және көбірек жетістікке жетіңіз!',
    motivational_desc: 'Әр қадамыңыз сізді мақсаттарыңызға жақындатады. Мотивацияда болыңыз!',
    highest_score: 'Ең жоғары ұпай',
    highest_score_value: 'Ең жақсы ұпай: 950 ұпай',
    cta_tasks_title: 'Жаңа тапсырмаларды қабылдаңыз!',
    cta_tasks_desc: 'Дағдыларыңызды арттыру үшін жаңа тапсырмалармен өзіңізді сынаңыз!',
    explore_tasks: 'Тапсырмаларды зерттеңіз',
    course_recommendations: 'Курс ұсыныстары',
    recommendation1: 'Жетілдірілген Python курсын көріңіз',
    recommendation2: 'Machine Learning негіздерін зерттеңіз',
    certificates: 'Сертификаттар',
    certificate1: 'Сертификат: Бағдарламалауға кіріспе, 10.10.2025',
    certificate2: 'Сертификат: Деректер ғылымы негіздері, 15.09.2025',

    // === Best Students Page (best-students.php) ===
    best_students_title: 'Ең үздік студенттер',
    rank: 'Рейтинг',
    avatar: 'Аватар',
    points: 'Жалпы ұпайлар',
    prev_page: 'Алдыңғы бет',
    next_page: 'Келесі бет',

    // === Settings Modal (profile.php, best-students.php, etc.) ===
    profile_settings: 'Профиль баптаулары',
    upload_avatar: 'Аватарды жүктеу',
    user_info: 'Сіздің деректеріңіз',
    username: 'Логин:',
    full_name: 'Аты-жөні:',
    class_label: 'Сынып:',
    edit_profile: 'Өңдеу',
    new_username: 'Жаңа логин',
    new_fullname: 'Жаңа Аты-жөні',
    class_select: 'Сынып',
    select_class_empty: '—',
    avatar_border_settings: 'Аватарды безендіру',
    standard: 'Standard',
    efpremium: 'EFPremium',
    border_color: 'Жақтау түсі',
    border_preview: 'Алдын ала қарау:',
    frame_rgb: 'RGB',
    efpremium_required_frames: 'Эксклюзивті жақтауларға қол жеткізу үшін EFPremium алыңыз!',
    get_premium: 'EFPremium алу',
    save_border: 'Жақтауды сақтау',
    
    // === Teacher Dashboard (teacher_dashboard.php) ===
    teacher_dashboard_title: 'Әзірлеу саласы',
    teacher_dashboard_desc: 'Мазмұнды басқару панеліне қош келдіңіз. Мұнда сіз студенттерге арналған материалдар жасай аласыз.',
    stat_books_loaded: 'Жүктелген кітаптар',
    stat_avg_rating: 'Орташа рейтинг',
    tools_title: 'Құралдар',
    add_book_title: 'Кітап қосу',
    add_book_desc: 'Жаңа PDF оқулық немесе әдістемелік құрал жүктеу.',
    my_publications_title: 'Менің жарияланымдарым',
    my_publications_desc: 'Кітапханадағы жүктелген материалдарыңызды қарау.',
    create_test_title: 'Тест жасау',
    create_test_desc: 'Интерактивті тапсырмалар конструкторы.',
    analytics_title: 'Аналитика',
    analytics_desc: 'Көру статистикасы және үлгерім.',
    dev_in_progress: 'Функция әзірленуде!',

    // === Add/Edit Book (add_book.php, edit_book.php) ===
    add_book_page_title: 'Кітап қосу',
    add_book_header: 'Жаңа кітап қосу',
    add_book_subheader: 'Кітапханаға материалды жариялау үшін пішінді толтырыңыз.',
    edit_book_page_title: 'Кітапты өңдеу',
    edit_book_header: 'Кітапты өңдеу',
    edit_book_subheader: 'Ақпаратты өзгертіңіз немесе жаңартылған файлдарды жүктеңіз.',
    book_title_label: 'Кітап атауы',
    book_title_placeholder: 'Мысалы: Физика 7 сынып. Механика',
    subject_label: 'Пән',
    select_subject_placeholder: 'Пәнді таңдаңыз',
    // Subjects
    subject_math: 'Математика',
    subject_algebra: 'Алгебра',
    subject_geometry: 'Геометрия',
    subject_physics: 'Физика',
    subject_chemistry: 'Химия',
    subject_biology: 'Биология',
    subject_english: 'Ағылшын тілі',
    subject_history: 'Тарих',
    subject_informatics: 'Информатика',
    subject_literature: 'Әдебиет',
    subject_geography: 'География',
    subject_russian: 'Орыс тілі',
    subject_russian_lit: 'Орыс әдебиеті',
    subject_russian_lang_lit: 'Орыс тілі мен әдебиеті',
    subject_kazakh: 'Қазақ тілі',
    subject_kazakh_lang_lit: 'Қазақ тілі мен әдебиеті',
    subject_natural_science: 'Жаратылыстану',
    subject_world_history: 'Дүниежүзі тарихы',
    subject_kazakh_history: 'Қазақстан тарихы',
    subject_global_comp: 'Ғаламдық құзыреттіліктер',
    subject_law_basics: 'Құқық негіздері',
    subject_self_knowledge: 'Өзін-өзі тану',
    subject_labor_training: 'Еңбекке баулу',
    subject_art: 'Бейнелеу өнері',
    subject_music: 'Музыка',
    subject_art_labor: 'Көркем еңбек',
    subject_pe: 'Дене шынықтыру',
    subject_military_training: 'Алғашқы әскери және технологиялық дайындық',
    // End Subjects
    class_label_form: 'Сынып',
    n_class: '{n} Сынып',
    languages_label: 'Кітап тілдері',
    lang_ru: 'Орысша',
    lang_kz: 'Қазақша',
    lang_en: 'Ағылшынша',
    short_desc_label: 'Қысқаша сипаттама (карточка үшін)',
    short_desc_placeholder: 'Ең көбі 150 таңба...',
    full_desc_label: 'Толық сипаттама',
    full_desc_placeholder: 'Оқу материалының толық сипаттамасы...',
    cover_label: 'Мұқаба (JPG, PNG)',
    cover_desc: 'Ұсынылатын өлшем: 300x450px (Тігінен)',
    file_label: 'Кітап файлы (PDF)',
    publish_button: 'Кітапты жариялау',
    save_button: 'Өзгерістерді сақтау',
    cancel_button: 'Болдырмау',
    edit_book_leave_empty: '(Өзгертпесеңіз, бос қалдырыңыз)',
    current_cover_label: 'Ағымдағы мұқаба:',
    current_file_label: 'Ағымдағы файл:',
    alert_book_published: 'Кітап сәтті жарияланды!',
    alert_book_saved: 'Өзгерістер сақталды!',
    alert_db_error: 'ДҚ Қатесі:',
    alert_upload_error: 'Файл жүктеу қатесі.',

    // === My Books (my_books.php) ===
    my_publications_page_title: 'Менің жарияланымдарым',
    my_publications_desc: 'Жүктелген кітаптарыңыз бен материалдарыңызды басқарыңыз',
    add_book_button: 'Қосу',
    edit_button: 'Өзг.',
    delete_button: 'Жою',
    view_button: 'Көру',
    empty_state_title: 'Сізде әлі жарияланымдар жоқ',
    empty_state_desc: 'Бірінші кітабыңызды немесе оқу материалыңызды жүктеңіз.',
    empty_state_add_button: 'Кітап қосу',
    confirm_delete_message: 'Бұл кітапты жойғыңыз келетініне сенімдісіз бе? Бұл әрекетті болдырмау мүмкін емес.',
    alert_delete_success: 'Кітап сәтті жойылды.',
    alert_delete_error: 'Жою қатесі. Сіз бұл кітаптың авторы емессіз.',

    // === Online Book (online-book.php) ===
    online_library_title: 'Онлайн Кітапхана',
    filter_class_label: 'Сынып',
    filter_all_classes: 'Барлық сыныптар',
    filter_search_label: 'Іздеу',
    filter_search_placeholder: 'Кітап атауы немесе пән...',
    filter_find_button: 'Табу',
    books_not_found: 'Кітаптар табылмады. Сүзгілерді өзгертіп көріңіз.',
    open_button: 'Ашу',

    // === Book Details (book_details.php) ===
    back_to_library: 'Кітапханаға оралу',
    read_online_button: 'Онлайн оқу',
    download_pdf_button: 'PDF жүктеп алу',
    author_support_notice: 'Автор қаралым үшін қолдау алады',
    rating_votes_label: '{n} дауыс негізінде',
    description_label: 'Материал сипаттамасы',
    your_rating_label: 'Материалға қойған бағаңыз',
    rating_5_star: 'Өте жақсы',
    rating_4_star: 'Жақсы',
    rating_3_star: 'Қалыпты',
    rating_2_star: 'Жаман',
    rating_1_star: 'Өте жаман',
    author_label: 'Жарияланым авторы',
    report_error_link: 'Қате таптыңыз ба? Шағымдану',
    report_error_alert: 'Шағымдану функциясы уақытша қолжетімсіз. Біз осымен жұмыс істеп жатырмыз!',
    alert_rating_login: 'Кітапты бағалау үшін кіріңіз.',

    // === Training Page (from old file) ===
    training: 'Оқыту',
    best_students: 'Ең үздік студенттер',
    training_title: 'Оқыту - EDU-Familiar.kz',
    filters: 'Сүзгілер',
    rating: 'Рейтинг',
    class_program: 'Сынып бағдарламасы',
    sort_by: 'Сұрыптау бойынша',
    new_courses: 'Жаңа курстар',
    old_courses: 'Ескі курстар',
    popular: 'Популярлы',
    search_placeholder: 'Курстарды іздеу...',
    course_rating: 'Рейтинг:',
    course_date: 'Жасалған:',
    course_teacher: 'Мұғалім:',
    no_courses: 'Курс табылмады.',
    online_book_title: 'Онлайн Кітап - EDU-Familiar.kz',
    online_book: 'Онлайн Кітап',
    books_list: 'Қолжетімді кітаптар',
    read_online: 'Онлайн оқу',
    download: 'Жүктеу',
    no_books: 'Қолжетімді кітап жоқ.',
    book_rating: 'Рейтинг:',
    book_class: 'Сынып:',

    // === Catalog (from old file) ===
    catalog_title: 'Каталог - EDU-Familiar.kz',
    catalog: 'Каталог',
    mugs: 'Кружкалар',
    mug1_name: 'Кружка "Мысық"',
    mug2_name: 'Кружка "Мотивация"',
    mug3_name: 'Кружка "Махаббат"',
    mug4_name: 'Кружка "Табиғат"',
    mug5_name: 'Кружка "Ғарыш"',
    mug6_name: 'Кружка "Минимализм"',
    backpacks: 'Рюкзактар',
    backpack1_name: 'Рюкзак "Қалалық"',
    backpack2_name: 'Рюкзак "Спорт"',
    backpack3_name: 'Рюкзак "Классика"',
    backpack4_name: 'Рюкзак "Саяхат"',
    backpack5_name: 'Рюкзак "Минимал"',
    backpack6_name: 'Рюкзак "Эко"',
    tshirts: 'Футболкалар',
    tshirt1_name: 'Футболка "Принт"',
    tshirt2_name: 'Футболка "Классика"',
    tshirt3_name: 'Футболка "Спорт"',
    tshirt4_name: 'Футболка "Винтаж"',
    tshirt5_name: 'Футболка "Минимализм"',
    tshirt6_name: 'Футболка "Эко"',
    caps: 'Қалпақтар',
    cap1_name: 'Қалпақ "Классика"',
    cap2_name: 'Қалпақ "Snapback"',
    cap3_name: 'Қалпақ "Бейсболка"',
    cap4_name: 'Қалпақ "Траки"',
    cap5_name: 'Қалпақ "Винтаж"',
    cap6_name: 'Қалпақ "Эко"',
    notebooks: 'Дәптерлер',
    notebook1_name: 'Дәптер А5 "Минимал"',
    notebook2_name: 'Дәптер А5 "Принт"',
    notebook3_name: 'Дәптер А6 "Саяхат"',
    notebook4_name: 'Дәптер А5 "Ғарыш"',
    notebook5_name: 'Дәптер А5 "Флора"',
    notebook6_name: 'Дәптер А6 "Минимализм"',
    show_more: 'Көбірек көрсету',
    all_shown: 'Барлық тауарлар көрсетілді',
  }
};


/**
 * --- НОВАЯ УЛУЧШЕННАЯ ФУНКЦИЯ ---
 * Она переводит:
 * 1. Обычный текст (innerText) через [data-i18n]
 * 2. Плейсхолдеры (placeholder) через [data-i18n-placeholder]
 * 3. Всплывающие подсказки (title) через [data-i18n-title]
 * 4. Значения кнопок (value) через [data-i18n-value]
 */
function setLanguage(lang) {
  localStorage.setItem('language', lang);
  document.documentElement.lang = lang;

  const translate = (element, attribute, translationKey) => {
    const key = element.getAttribute(attribute);
    if (translations[lang] && translations[lang][key]) {
      element[translationKey] = translations[lang][key];
    }
  };

  // 1. Обычный текст
  document.querySelectorAll('[data-i18n]').forEach(element => {
    translate(element, 'data-i18n', 'innerText');
  });

  // 2. Плейсхолдеры
  document.querySelectorAll('[data-i18n-placeholder]').forEach(element => {
    translate(element, 'data-i18n-placeholder', 'placeholder');
  });

  // 3. Всплывающие подсказки (title)
  document.querySelectorAll('[data-i18n-title]').forEach(element => {
    translate(element, 'data-i18n-title', 'title');
  });
  
  // 4. Значения (для <input type="submit">)
  document.querySelectorAll('[data-i18n-value]').forEach(element => {
    translate(element, 'data-i18n-value', 'value');
  });

  // Обновляем все <select> на странице
  document.querySelectorAll('.lang-select').forEach(select => {
    select.value = lang;
  });
}

document.addEventListener('DOMContentLoaded', () => {
  const savedLang = localStorage.getItem('language') || 'en';
  setLanguage(savedLang);

  document.querySelectorAll('.lang-select').forEach(select => {
    select.addEventListener('change', (e) => {
      const lang = e.target.value;
      setLanguage(lang);
    });
  });
});